### PR TITLE
Adding `dotgpg create`

### PR DESCRIPTION
**Pull request by envatopoho**
This will add the ability to call dotgpg from other programs and scripts and have it create encrypted files without having to use the editor.

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@envatopoho Thanks so much!

Minor request, can the API be: `echo foo | dotgpg create a.gpg` ?

That feels more bashy to me.

**Comment by envatopoho** [comment]
For sure - good call have updated the code to do it this way. :)

**Comment by ConradIrwin** [comment]
:+1:

**Comment by ConradIrwin** [comment]
released in 0.7.0

**Comment by ConradIrwin** [comment]
P.S. I've added you as a collaborator, thanks for the great first PR. Feel free to tidy things up and make this repo feel like home, please send PRs for big changes, but small stuff, go wild.

**Comment by envatopoho** [comment]
Cheers - will do.

**Pull request merged**
